# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\msys64\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\msys64\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\vverd\Downloads\melonDS-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\vverd\Downloads\melonDS-master\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\msys64\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\msys64\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\vverd\Downloads\melonDS-master\build\CMakeFiles C:\Users\vverd\Downloads\melonDS-master\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\vverd\Downloads\melonDS-master\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f src\CMakeFiles\core.dir\build.make src/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named teakra

# Build rule for target.
teakra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 teakra
.PHONY : teakra

# fast build rule for target.
teakra/fast:
	$(MAKE) $(MAKESILENT) -f src\teakra\src\CMakeFiles\teakra.dir\build.make src/teakra/src/CMakeFiles/teakra.dir/build
.PHONY : teakra/fast

#=============================================================================
# Target rules for targets named teakra_c

# Build rule for target.
teakra_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 teakra_c
.PHONY : teakra_c

# fast build rule for target.
teakra_c/fast:
	$(MAKE) $(MAKESILENT) -f src\teakra\src\CMakeFiles\teakra_c.dir\build.make src/teakra/src/CMakeFiles/teakra_c.dir/build
.PHONY : teakra_c/fast

#=============================================================================
# Target rules for targets named melonDS

# Build rule for target.
melonDS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 melonDS
.PHONY : melonDS

# fast build rule for target.
melonDS/fast:
	$(MAKE) $(MAKESILENT) -f src\frontend\qt_sdl\CMakeFiles\melonDS.dir\build.make src/frontend/qt_sdl/CMakeFiles/melonDS.dir/build
.PHONY : melonDS/fast

#=============================================================================
# Target rules for targets named melonDS_autogen_timestamp_deps

# Build rule for target.
melonDS_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 melonDS_autogen_timestamp_deps
.PHONY : melonDS_autogen_timestamp_deps

# fast build rule for target.
melonDS_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src\frontend\qt_sdl\CMakeFiles\melonDS_autogen_timestamp_deps.dir\build.make src/frontend/qt_sdl/CMakeFiles/melonDS_autogen_timestamp_deps.dir/build
.PHONY : melonDS_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named melonDS_autogen

# Build rule for target.
melonDS_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 melonDS_autogen
.PHONY : melonDS_autogen

# fast build rule for target.
melonDS_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src\frontend\qt_sdl\CMakeFiles\melonDS_autogen.dir\build.make src/frontend/qt_sdl/CMakeFiles/melonDS_autogen.dir/build
.PHONY : melonDS_autogen/fast

#=============================================================================
# Target rules for targets named net-utils

# Build rule for target.
net-utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 net-utils
.PHONY : net-utils

# fast build rule for target.
net-utils/fast:
	$(MAKE) $(MAKESILENT) -f net\CMakeFiles\net-utils.dir\build.make net/CMakeFiles/net-utils.dir/build
.PHONY : net-utils/fast

#=============================================================================
# Target rules for targets named net-utils_autogen_timestamp_deps

# Build rule for target.
net-utils_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 net-utils_autogen_timestamp_deps
.PHONY : net-utils_autogen_timestamp_deps

# fast build rule for target.
net-utils_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f net\CMakeFiles\net-utils_autogen_timestamp_deps.dir\build.make net/CMakeFiles/net-utils_autogen_timestamp_deps.dir/build
.PHONY : net-utils_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named net-utils_autogen

# Build rule for target.
net-utils_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 net-utils_autogen
.PHONY : net-utils_autogen

# fast build rule for target.
net-utils_autogen/fast:
	$(MAKE) $(MAKESILENT) -f net\CMakeFiles\net-utils_autogen.dir\build.make net/CMakeFiles/net-utils_autogen.dir/build
.PHONY : net-utils_autogen/fast

#=============================================================================
# Target rules for targets named slirp

# Build rule for target.
slirp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 slirp
.PHONY : slirp

# fast build rule for target.
slirp/fast:
	$(MAKE) $(MAKESILENT) -f net\libslirp\CMakeFiles\slirp.dir\build.make net/libslirp/CMakeFiles/slirp.dir/build
.PHONY : slirp/fast

#=============================================================================
# Target rules for targets named slirp_autogen_timestamp_deps

# Build rule for target.
slirp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 slirp_autogen_timestamp_deps
.PHONY : slirp_autogen_timestamp_deps

# fast build rule for target.
slirp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f net\libslirp\CMakeFiles\slirp_autogen_timestamp_deps.dir\build.make net/libslirp/CMakeFiles/slirp_autogen_timestamp_deps.dir/build
.PHONY : slirp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named slirp_autogen

# Build rule for target.
slirp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 slirp_autogen
.PHONY : slirp_autogen

# fast build rule for target.
slirp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f net\libslirp\CMakeFiles\slirp_autogen.dir\build.make net/libslirp/CMakeFiles/slirp_autogen.dir/build
.PHONY : slirp_autogen/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... melonDS_autogen
	@echo ... melonDS_autogen_timestamp_deps
	@echo ... net-utils_autogen
	@echo ... net-utils_autogen_timestamp_deps
	@echo ... slirp_autogen
	@echo ... slirp_autogen_timestamp_deps
	@echo ... core
	@echo ... melonDS
	@echo ... net-utils
	@echo ... slirp
	@echo ... teakra
	@echo ... teakra_c
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

